/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: horse_water (https://sketchfab.com/keitamamizu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magic-book-0cbf26f5a41f4d3e8e05b07cba98e63c
Title: 魔導書 (Magic Book)
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function MagicBookModel(props) {
    const { nodes, materials } = useGLTF('/models/magic_book.glb')

    const modelRef = useRef();
    const magicStormRef = useRef();
    const MagicParticleRef = useRef();


    ////useframe for animation here:
    useFrame((state, delta, xrFrame) => {
        modelRef.current.position.y = -0.7 + Math.sin(state.clock.elapsedTime) * 0.15
        // console.log(state.clock);


        // / magic storm animation
        magicStormRef.current.rotation.y = -0.001 + Math.sin(state.clock.elapsedTime) * 0.15

        MagicParticleRef.current.rotation.x = -0.001 + Math.sin(state.clock.elapsedTime) * 0.5


    })







    return (
        <group {...props} dispose={null}>
            <group
                ref={modelRef}
                position={[0, -0.7, 0]}
                scale={[0.002, 0.002, 0.002]}
                rotation={[0.5, 0, 0]}
                renderOrder={10}


            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cover_Cover_0.geometry}
                    material={materials.Cover}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[568.123, 568.123, 100]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001_Paper_Block_0.geometry}
                    material={materials.Paper_Block}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002_Paper_Block_0.geometry}
                    material={materials.Paper_Block}
                    position={[0, 14.501, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.PaperLeft_Paper_0.geometry}
                    material={materials.Paper}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003_Paper_Block_0.geometry}
                    material={materials.Paper_Block}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CoverCorner_Cover_Corner_0.geometry}
                    material={materials.Cover_Corner}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[568.123, 568.123, 100]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.PaperRight_Paper_0.geometry}
                    material={materials.Paper}
                    rotation={[-Math.PI / 2, 0, -Math.PI]}
                    scale={100}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004_Paper_Block_0.geometry}
                    material={materials.Paper_Block}
                    rotation={[-Math.PI / 2, 0, -Math.PI]}
                    scale={100}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005_Paper_Block_0.geometry}
                    material={materials.Paper_Block}
                    position={[0, 14.501, 0]}
                    rotation={[-Math.PI / 2, 0, -Math.PI]}
                    scale={100}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube006_Paper_Block_0.geometry}
                    material={materials.Paper_Block}
                    rotation={[-Math.PI / 2, 0, -Math.PI]}
                    scale={100}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Magic_Circle_Magic_Circle_0.geometry}
                    material={materials.Magic_Circle}
                    position={[0, 349.341, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={498.824}
                />
                <mesh
                    ref={magicStormRef}
                    castShadow
                    receiveShadow
                    geometry={nodes.Magic_Storm_Magic_Storm_0.geometry}
                    material={materials.Magic_Storm}
                    position={[0, 285.089, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[465.909, 465.909, 100]}
                />
                <mesh
                    castShadow
                    receiveShadow

                    ref={MagicParticleRef}
                    geometry={nodes.Magic_Particle_Magic_Particle_0.geometry}
                    material={materials.Magic_Particle}
                    position={[0, 559.955, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/models/magic_book.glb')
